using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Windows.Media.Imaging;
using Edi.Core;
using Edi.Core.Services;

namespace Edi.Forms
{
    // Build .lnk + .cmd + .ico artifacts for the right-click "Create shortcut…" feature.
    // Output layout (per game, accumulates so reusing the same name overwrites in place):
    //   <OutputDir>\shortcuts\<safeName>.cmd     ← launcher script the .lnk points at
    //   <OutputDir>\shortcuts\<safeName>.ico     ← icon written for the .lnk
    internal static class GameShortcuts
    {
        public static string ShortcutsDir => Path.Combine(Edi.Core.Edi.OutputDir, "shortcuts");

        private static string SafeName(string s)
        {
            var safe = string.Join("_", (s ?? "game").Split(Path.GetInvalidFileNameChars()));
            return string.IsNullOrWhiteSpace(safe) ? "game" : safe;
        }

        // Writes a .cmd that fires off each "ALSO START" program (non-blocking, via `start ""`)
        // and then the target itself. Programs launch first so they're already initializing
        // by the time the game's main process spawns.
        public static string WriteLauncherCmd(GameInfo g, string targetPath, string targetArgs, IEnumerable<QuickProgram> alsoStart)
        {
            Directory.CreateDirectory(ShortcutsDir);
            var file = Path.Combine(ShortcutsDir, SafeName(g.Name) + ".cmd");

            var sb = new StringBuilder();
            sb.AppendLine("@echo off");
            sb.AppendLine("REM Auto-generated by EDI \"Create shortcut\". Safe to edit; re-running");
            sb.AppendLine("REM the shortcut wizard for this game will overwrite it.");
            sb.AppendLine();

            // Helper programs first (don't wait — fire and forget).
            foreach (var p in alsoStart)
            {
                if (string.IsNullOrWhiteSpace(p?.Path)) continue;
                var workDir = SafeDir(p.Path);
                sb.AppendLine($"REM auto-start: {Escape(p.Name)}");
                if (workDir != null) sb.AppendLine($"start \"\" /D \"{workDir}\" \"{p.Path}\"");
                else                  sb.AppendLine($"start \"\" \"{p.Path}\"");
            }

            // Main target (the game / launch-option). Same fire-and-forget pattern so the
            // launcher window closes immediately instead of staying parked on the desktop.
            var gameWorkDir = SafeDir(targetPath);
            sb.AppendLine();
            sb.AppendLine($"REM launch target: {Escape(g.Name)}");
            var argsSuffix = string.IsNullOrWhiteSpace(targetArgs) ? "" : " " + targetArgs;
            if (gameWorkDir != null)
                sb.AppendLine($"start \"\" /D \"{gameWorkDir}\" \"{targetPath}\"{argsSuffix}");
            else
                sb.AppendLine($"start \"\" \"{targetPath}\"{argsSuffix}");

            File.WriteAllText(file, sb.ToString(), Encoding.UTF8);
            return file;
        }

        private static string? SafeDir(string fileOrUrl)
        {
            if (string.IsNullOrWhiteSpace(fileOrUrl)) return null;
            if (fileOrUrl.StartsWith("http://", StringComparison.OrdinalIgnoreCase) ||
                fileOrUrl.StartsWith("https://", StringComparison.OrdinalIgnoreCase)) return null;
            try
            {
                var d = Path.GetDirectoryName(fileOrUrl);
                return string.IsNullOrWhiteSpace(d) ? null : d;
            }
            catch { return null; }
        }

        private static string Escape(string? s) => (s ?? "").Replace("\r", "").Replace("\n", " ");

        // .lnk's IconLocation field needs an .ico (or an exe to extract from). If the game's
        // IconPath is already .ico we use it directly; otherwise we render a 256px PNG-in-ICO
        // wrapper. If no source is available we hand back null and the .lnk writer falls back
        // to the game's exe icon — same chain the cards already use.
        public static string? EnsureIcoForGame(GameInfo g)
        {
            string? src = null;
            if (!string.IsNullOrWhiteSpace(g.IconPath) && File.Exists(g.IconPath)) src = g.IconPath;
            if (src == null)
            {
                // Folder icon → .ico in folder → exe icon: same priority the card resolver uses.
                var folder = !string.IsNullOrWhiteSpace(g.GalleryPath) && Directory.Exists(g.GalleryPath)
                    ? g.GalleryPath
                    : (!string.IsNullOrWhiteSpace(g.ExePath) ? Path.GetDirectoryName(g.ExePath) : null);
                if (Directory.Exists(folder))
                {
                    try
                    {
                        var ico = Directory.EnumerateFiles(folder, "*.ico", SearchOption.TopDirectoryOnly).FirstOrDefault();
                        if (ico != null) src = ico;
                    }
                    catch { }
                }
            }
            if (src == null) return null;

            // Already an .ico → just return it directly.
            if (Path.GetExtension(src).Equals(".ico", StringComparison.OrdinalIgnoreCase) && File.Exists(src))
                return src;

            // Otherwise convert the PNG/JPG to a single-frame .ico (PNG-in-ICO, Vista+ format).
            try
            {
                Directory.CreateDirectory(ShortcutsDir);
                var dst = Path.Combine(ShortcutsDir, SafeName(g.Name) + ".ico");
                if (WritePngBackedIco(src, dst, 256)) return dst;
            }
            catch { }
            return null;
        }

        // PNG-in-ICO wrapper: 6-byte header + 16-byte ICONDIRENTRY + raw PNG bytes.
        // Windows Vista+ Explorer reads the embedded PNG straight from the .ico — no per-size
        // BMP frames needed, so this stays a few KB regardless of the source resolution.
        private static bool WritePngBackedIco(string sourceImage, string targetIco, int size)
        {
            try
            {
                // Decode the source and re-encode at the requested edge so the ICO carries
                // a square, web-compatible PNG payload (handles non-square or huge inputs).
                var bi = new BitmapImage();
                bi.BeginInit();
                bi.CacheOption = BitmapCacheOption.OnLoad;
                bi.UriSource = new Uri(sourceImage);
                bi.DecodePixelWidth = size;
                bi.EndInit();
                bi.Freeze();

                using var pngStream = new MemoryStream();
                var enc = new PngBitmapEncoder();
                enc.Frames.Add(BitmapFrame.Create(bi));
                enc.Save(pngStream);
                var pngBytes = pngStream.ToArray();

                using var ico = File.Create(targetIco);
                using var bw  = new BinaryWriter(ico);
                bw.Write((short)0);          // reserved
                bw.Write((short)1);          // type = ICON
                bw.Write((short)1);          // image count

                byte dim = (byte)(size >= 256 ? 0 : size);  // 0 == 256 in the .ico header
                bw.Write(dim);               // width
                bw.Write(dim);               // height
                bw.Write((byte)0);           // color count (0 = >256 / true color)
                bw.Write((byte)0);           // reserved
                bw.Write((short)1);          // planes
                bw.Write((short)32);         // bit count
                bw.Write(pngBytes.Length);   // image size
                bw.Write(22);                // offset (6 header + 16 entry)
                bw.Write(pngBytes);
                return true;
            }
            catch { return false; }
        }

        // Build the .lnk via WScript.Shell COM. Sets the icon to .ico (or the exe path with
        // index 0 when no .ico is available). Writes to the user-chosen savePath.
        public static void WriteLnk(string savePath, string targetCmd, GameInfo g, string? iconFile)
        {
            try { Directory.CreateDirectory(Path.GetDirectoryName(savePath)!); } catch { }

            Type? wshType = Type.GetTypeFromProgID("WScript.Shell");
            if (wshType == null)
                throw new InvalidOperationException("WScript.Shell COM is unavailable on this system.");
            dynamic shell = Activator.CreateInstance(wshType)!;
            try
            {
                dynamic lnk = shell.CreateShortcut(savePath);
                try
                {
                    lnk.TargetPath = targetCmd;
                    lnk.WorkingDirectory = Path.GetDirectoryName(targetCmd) ?? "";
                    lnk.Description = $"Launch {g.Name}";
                    // 7 = SW_SHOWMINNOACTIVE → the helper .cmd flashes minimized so the desktop
                    // doesn't get a stray console window. Ignored when targeting actual exes.
                    lnk.WindowStyle = 7;

                    string? iconArg = null;
                    if (!string.IsNullOrWhiteSpace(iconFile) && File.Exists(iconFile))
                        iconArg = iconFile + ",0";
                    else if (!string.IsNullOrWhiteSpace(g.ExePath) && File.Exists(g.ExePath))
                        iconArg = g.ExePath + ",0";
                    if (iconArg != null) lnk.IconLocation = iconArg;

                    lnk.Save();
                }
                finally { System.Runtime.InteropServices.Marshal.FinalReleaseComObject(lnk); }
            }
            finally { System.Runtime.InteropServices.Marshal.FinalReleaseComObject(shell); }
        }
    }
}
