<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
	<OutputType>WinExe</OutputType>
	<TargetFramework>net8.0-windows7.0</TargetFramework>
	<Nullable>enable</Nullable>
	<UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <AssemblyName>Edi</AssemblyName>
	  <Version>1.0.2</Version>
	  <AssemblyVersion>1.0.2</AssemblyVersion>
	  <FileVersion>1.0.2</FileVersion>
    <ApplicationIcon>Edi.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Edi.ico"/>
    <Resource Include="intiface_icon.png"/>
  </ItemGroup>

  <ItemGroup>
    <None Remove="certificate.pfx" />
  </ItemGroup>
  <ItemGroup>
    <_WebToolingArtifacts Remove="Properties\PublishProfiles\OneClick.pubxml" />
  </ItemGroup>
  <ItemGroup>
	<PackageReference Include="Fody" Version="6.9.2">
		<PrivateAssets>all</PrivateAssets>
		<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.4" />
    <PackageReference Include="WpfAnimatedGif" Version="2.0.2" />
    <PackageReference Include="QRCoder" Version="1.6.0" />
    <PackageReference Include="PdfPig" Version="0.1.9" />
    <PackageReference Include="Dirkster.AvalonDock" Version="4.72.1" />
    <PackageReference Include="Dirkster.AvalonDock.Themes.VS2013" Version="4.72.1" />
    <PackageReference Include="PropertyChanged.Fody" Version="4.1.0" />
    <PackageReference Include="Serilog" Version="4.2.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.4" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="9.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Edi.Core\Edi.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="certificate.pfx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>